version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=cakephp

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ./app:/app
    - ./images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    ports:
    - "8080:80"
    depends_on:
      - db

  php:
    container_name: php
    build:
      context: ./
      dockerfile: ./images/php/php-fpm.dockerfile
    volumes:
    - ./app:/app
    links:
      - db:db
    depends_on:
      - db

  composer:
    container_name: composer
    build:
      context: ./
      dockerfile: ./images/composer/composer.dockerfile
    command: install
    volumes:
    - ./app:/app